
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-dep
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      containers:
      - name: my-nginx
        image: nginx
        
---

apiVersion: v1
kind: Service
metadata:
  name: nport
spec:

  type: NodePort
  selector:
    app: my-dep
  ports:
  - port: 80
    targetPort: 80
