apiVersion: v1
kind: PersistentVolume
metadata:
  name: pers
  #labels: 
    #type: local
spec:
  capacity:
   storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: "/a/b"
