apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudpv
  labels:
    type: AWSpvc
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  awsElasticBlockStore:
    volumeID: vol-0cac83a1602347d3c

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvccloud
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
