apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod-2node
  labels:
    region: us-west-1a
  namespace: cloudnamespace
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
   nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: region
         operator: In
         values:
         - us-west-1a
        